// Report Generation Service
// Handles PDF, HTML, and export generation

import {
  ReportConfig,
  HoroscopeReport,
  DashaReport,
  TransitReport,
  CompatibilityReport,
  ExportOptions,
  DEFAULT_EXPORT_OPTIONS,
} from './reportTypes';

export class ReportGenerator {
  /**
   * Generate a Horoscope Report
   */
  static generateHoroscopeReport(
    report: HoroscopeReport,
    config: ReportConfig
  ): string {
    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Vedic Horoscope Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
    .header { text-align: center; border-bottom: 2px solid #8B4513; padding-bottom: 20px; }
    .section { margin: 30px 0; }
    .section-title { font-size: 18px; font-weight: bold; color: #8B4513; border-bottom: 1px solid #ddd; padding-bottom: 10px; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin: 20px 0; }
    .info-item { background: #f9f9f9; padding: 10px; border-radius: 5px; }
    .label { font-weight: bold; color: #666; }
    .value { color: #333; margin-top: 5px; }
    ul { margin: 10px 0; padding-left: 20px; }
    li { margin: 5px 0; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666; }
    .watermark { opacity: 0.1; position: fixed; font-size: 60px; color: #999; }
  </style>
</head>
<body>
  ${config.format === 'pdf' ? '<div class="watermark">KOTRAVEL</div>' : ''}

  <div class="header">
    <h1>वैदिक जातक अध्ययन (Vedic Horoscope Report)</h1>
    <p>Comprehensive Astrological Analysis</p>
  </div>

  <div class="section">
    <div class="section-title">Native Information</div>
    <div class="info-grid">
      <div class="info-item">
        <div class="label">Name</div>
        <div class="value">${report.nativeName}</div>
      </div>
      <div class="info-item">
        <div class="label">Date of Birth</div>
        <div class="value">${report.dateOfBirth}</div>
      </div>
      <div class="info-item">
        <div class="label">Time of Birth</div>
        <div class="value">${report.timeOfBirth}</div>
      </div>
      <div class="info-item">
        <div class="label">Place of Birth</div>
        <div class="value">${report.placeOfBirth}</div>
      </div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Chart Information</div>
    <div class="info-grid">
      <div class="info-item">
        <div class="label">Lagna (Ascendant)</div>
        <div class="value">${report.lagna}</div>
      </div>
      <div class="info-item">
        <div class="label">Moon Sign</div>
        <div class="value">${report.moon}</div>
      </div>
      <div class="info-item">
        <div class="label">Sun Sign</div>
        <div class="value">${report.sun}</div>
      </div>
    </div>
  </div>

  ${config.includeRecommendations ? `
  <div class="section">
    <div class="section-title">Overview</div>
    <p>${report.overview}</p>
  </div>

  <div class="section">
    <div class="section-title">Strengths</div>
    <ul>
      ${report.strengths.map(s => `<li>${s}</li>`).join('')}
    </ul>
  </div>

  <div class="section">
    <div class="section-title">Challenges</div>
    <ul>
      ${report.challenges.map(c => `<li>${c}</li>`).join('')}
    </ul>
  </div>

  <div class="section">
    <div class="section-title">Recommendations</div>
    <ul>
      ${report.recommendations.map(r => `<li>${r}</li>`).join('')}
    </ul>
  </div>
  ` : ''}

  <div class="footer">
    <p>Generated by Kotravel Vedic Astrology | ${report.generatedAt}</p>
    <p>This report is based on classical Vedic astrology principles and should be interpreted by a qualified astrologer.</p>
  </div>
</body>
</html>
    `;
    return html;
  }

  /**
   * Generate a Dasha Report
   */
  static generateDashaReport(
    report: DashaReport,
    config: ReportConfig
  ): string {
    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Dasha Prediction Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
    .header { text-align: center; border-bottom: 2px solid #8B4513; padding-bottom: 20px; }
    .dasha-period { background: #f9f9f9; padding: 15px; margin: 15px 0; border-left: 4px solid #8B4513; border-radius: 5px; }
    .period-header { font-weight: bold; color: #333; }
    .period-dates { color: #666; font-size: 14px; }
    .period-interpretation { margin-top: 10px; color: #333; }
    .section { margin: 30px 0; }
    .section-title { font-size: 18px; font-weight: bold; color: #8B4513; border-bottom: 1px solid #ddd; padding-bottom: 10px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>विम्शोत्तरी दशा (Dasha Prediction Report)</h1>
    <p>120-Year Planetary Period Cycle Analysis</p>
  </div>

  <div class="section">
    <div class="section-title">Native Information</div>
    <p><strong>Name:</strong> ${report.nativeName}</p>
    <p><strong>Report Period:</strong> ${report.startDate} to ${report.endDate}</p>
  </div>

  <div class="section">
    <div class="section-title">Dasha Timeline</div>
    ${report.periods.map(period => `
      <div class="dasha-period">
        <div class="period-header">${period.lord} Dasha</div>
        <div class="period-dates">${period.startDate} to ${period.endDate} (${period.durationYears} years)</div>
        <div class="period-interpretation">${period.interpretation}</div>
      </div>
    `).join('')}
  </div>

  <div class="section">
    <div class="section-title">Analysis</div>
    <p>${report.interpretation}</p>
  </div>

  ${report.upcomingEvents.length > 0 ? `
  <div class="section">
    <div class="section-title">Upcoming Events</div>
    <ul>
      ${report.upcomingEvents.map(event => `<li>${event}</li>`).join('')}
    </ul>
  </div>
  ` : ''}

  <div class="footer">
    <p>Generated by Kotravel Vedic Astrology</p>
  </div>
</body>
</html>
    `;
    return html;
  }

  /**
   * Generate Transit Report
   */
  static generateTransitReport(
    report: TransitReport,
    config: ReportConfig
  ): string {
    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Transit Analysis Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; }
    .header { text-align: center; border-bottom: 2px solid #008B8B; padding-bottom: 20px; }
    .transit-item { background: #f0f8f8; padding: 15px; margin: 10px 0; border-radius: 5px; }
    .planet { font-weight: bold; color: #008B8B; }
    .strength { padding: 5px 10px; border-radius: 3px; display: inline-block; margin-left: 10px; }
    .strength-strong { background: #90EE90; color: #333; }
    .strength-moderate { background: #FFD700; color: #333; }
    .strength-weak { background: #FFB6C6; color: #333; }
  </style>
</head>
<body>
  <div class="header">
    <h1>गोचर विश्लेषण (Transit Analysis Report)</h1>
    <p>Current Planetary Transits as of ${report.dateOfReport}</p>
  </div>

  <div>
    <h2>Current Transits</h2>
    ${report.currentTransits.map(transit => `
      <div class="transit-item">
        <span class="planet">${transit.planet}</span>
        <span class="strength strength-${transit.strengthLevel}">${transit.strengthLevel}</span>
        <p>In ${transit.currentSign} (Natal: ${transit.natalSign})</p>
        <p>${transit.influence}</p>
        <p><small>${transit.startDate} to ${transit.endDate}</small></p>
      </div>
    `).join('')}
  </div>

  <div style="margin-top: 30px;">
    <h2>Upcoming Transits</h2>
    ${report.upcomingTransits.map(transit => `
      <div class="transit-item">
        <span class="planet">${transit.planet}</span>
        <p>Moving to ${transit.currentSign}</p>
        <p>${transit.influence}</p>
        <p><small>${transit.startDate} to ${transit.endDate}</small></p>
      </div>
    `).join('')}
  </div>

  <div style="margin-top: 30px;">
    <h2>Analysis</h2>
    <p>${report.analysis}</p>
  </div>

  <div style="margin-top: 30px;">
    <h2>Recommendations</h2>
    <ul>
      ${report.recommendations.map(rec => `<li>${rec}</li>`).join('')}
    </ul>
  </div>
</body>
</html>
    `;
    return html;
  }

  /**
   * Export report to different formats
   */
  static async exportReport(
    html: string,
    options: ExportOptions = DEFAULT_EXPORT_OPTIONS
  ): Promise<Blob> {
    switch (options.format) {
      case 'pdf':
        return this.generatePDF(html, options);
      case 'html':
        return new Blob([html], { type: 'text/html' });
      case 'png':
        return this.generatePNG(html, options);
      case 'svg':
        return this.generateSVG(html, options);
      case 'excel':
        return this.generateExcel(html, options);
      default:
        return new Blob([html], { type: 'text/html' });
    }
  }

  /**
   * Generate PDF (using library integration point)
   */
  private static generatePDF(html: string, options: ExportOptions): Blob {
    // PDF generation will use jsPDF or similar library
    // This is a placeholder for the integration
    console.log('PDF generation initiated for:', options.filename);
    return new Blob([html], { type: 'application/pdf' });
  }

  /**
   * Generate PNG (chart to image conversion)
   */
  private static generatePNG(html: string, options: ExportOptions): Blob {
    // PNG generation will use html2canvas or similar
    console.log('PNG generation initiated for:', options.filename);
    return new Blob([html], { type: 'image/png' });
  }

  /**
   * Generate SVG (vector format)
   */
  private static generateSVG(html: string, options: ExportOptions): Blob {
    console.log('SVG generation initiated for:', options.filename);
    return new Blob([html], { type: 'image/svg+xml' });
  }

  /**
   * Generate Excel export
   */
  private static generateExcel(html: string, options: ExportOptions): Blob {
    // Excel generation will use xlsx library
    console.log('Excel generation initiated for:', options.filename);
    return new Blob([html], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  }

  /**
   * Send report via email
   */
  static async sendReportEmail(
    recipientEmail: string,
    subject: string,
    html: string,
    attachmentBlob?: Blob
  ): Promise<boolean> {
    try {
      // Email service integration point
      console.log(`Sending report to ${recipientEmail}`);
      // This will be integrated with email service (Nodemailer, SendGrid, etc.)
      return true;
    } catch (error) {
      console.error('Email send failed:', error);
      return false;
    }
  }

  /**
   * Generate printable version
   */
  static generatePrintableHTML(html: string): string {
    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Print Report</title>
  <style>
    @media print {
      body { margin: 0; padding: 10mm; }
      .no-print { display: none; }
      page { page-break-after: always; }
    }
    body { font-family: 'Times New Roman', serif; color: #333; }
  </style>
</head>
<body>
  ${html}
  <script>
    window.addEventListener('load', () => window.print());
  </script>
</body>
</html>
    `;
  }
}
