export const RASI_SHORT: Record<string, string> = {
  Mesha: 'மே',
  Vrishabha: 'ரி',
  Mithuna: 'மி',
  Karkataka: 'க',
  Simha: 'சி',
  Kanya: 'க',
  Tula: 'து',
  Vrischika: 'வி',
  Dhanu: 'த',
  Makara: 'ம',
  Kumbha: 'கு',
  Meena: 'மீ',
};

export const POINT_LABEL: Record<string, string> = {
  Lagna: 'லக்னம்',
  Sun: 'சூரியன்',
  Moon: 'சந்திரன்',
  Mars: 'செவ்வாய்',
  Mercury: 'புதன்',
  Jupiter: 'குரு',
  Venus: 'சுக்கிரன்',
  Saturn: 'சனி',
  Rahu: 'ராகு',
  Ketu: 'கேது',
};

export const RASI_FULL: Record<string, string> = {
  Mesha: 'மேஷ (Aries)',
  Vrishabha: 'ரிஷபம் (Taurus)',
  Mithuna: 'மிதுனம் (Gemini)',
  Karkataka: 'கடகம் (Cancer)',
  Simha: 'சிம்மம் (Leo)',
  Kanya: 'கன்னி (Virgo)',
  Tula: 'துலை (Libra)',
  Vrischika: 'விருச்சிகம் (Scorpio)',
  Dhanu: 'தனுஷ் (Sagittarius)',
  Makara: 'மகரம் (Capricorn)',
  Kumbha: 'கும்பம் (Aquarius)',
  Meena: 'மீனம் (Pisces)',
};

export const NAKSHATRA_NAMES: Record<number, string> = {
  1: 'அஸ்வினி',
  2: 'பரணி',
  3: 'கார்த்திகை',
  4: 'ரோஹிணி',
  5: 'மிருகசீரிஷம்',
  6: 'ஆர்த்ரா',
  7: 'புனர்வசு',
  8: 'புஷ்யம்',
  9: 'ஆஸ்லேஷை',
  10: 'மகம்',
  11: 'பூர்வ பல்குனி',
  12: 'உத்தர பல்குனி',
  13: 'ஹஸ்தம்',
  14: 'சித்திரை',
  15: 'சுவாதி',
  16: 'விசாகம்',
  17: 'அனுராதை',
  18: 'ஜ்யேஷ்டை',
  19: 'மூலம்',
  20: 'பூர்வாஷாடை',
  21: 'உத்தராஷாடை',
  22: 'சிரவணம்',
  23: 'தனிஷ்டை',
  24: 'சதயம்',
  25: 'பூர்வ பட்ரபதம்',
  26: 'உத்தர பட்ரபதம்',
  27: 'ரேவதி',
};
